### ISSUE TITLE
How's the crawler script ran ?

### ISSUE THREAD

**Issue by subins2000** [vanangamudi/newspaper-crawler-scripts#3]
I was trying to make a scraper for dheshabhimani.com

Copied [this script](https://github.com/vanangamudi/newspaper-crawler-scripts/blob/master/tamil/crawler-viduthalai4.py) from tamil folder, But running the script yields :

```
ModuleNotFoundError: No module named 'config'
```

How is the crawler scripts run ? config.py is in the root folder. A little bit of doc on this would be helpful.

**Comment by vanangamudi** [comment]
Please add `..` in PYTHONPATH so that, config in the root directory is accessible to the script. I will add this to the README.

`$ export PYTHONPATH=$PYTHONPATH:..`

**Comment by adamshamsudeen** [comment]
Instead of going the adding to PYTHONPATH manually, let's just add this line to the code.
```
import sys
sys.path.append('../')
```

**Comment by adamshamsudeen** [comment]
I have updated the script.

**Comment by subins2000** [comment]
@adamshamsudeen One more thing, I need to test the script to see whether it works. But it seems to download everything before the extraction. Is there a way to limit the crawled URLs to quickly test it out ?
