### ISSUE TITLE
Directory creation in Windows: Error

### ISSUE THREAD

**Issue by simran0117** [vanangamudi/newspaper-crawler-scripts#34]
makedir from linux uses '/' whereas Windows uses '\\' for paths in the creation of files and folders in a directory.
So instead of hard coding it for Windows and Linux separately, We'd like to have os.join to detect the os and choose the right option in the python script.

**Comment by meain** [comment]
Issues fixed in main `crawler.py` and in malayalam oneindia file.

For every other files its pretty much about replacing `/` with `os.sep` in the respective ones.
